First, move within a simulation directory that contains a sub-directory 'halo/' that contains rockstar halo catalog files. By default, the code assumes that the raw text halo files that Rockstar produces have been converted to hdf5 format and live in halo/rockstar_dm/catalog_hdf5/

Currently, I run Rockstar halo finder using only dark-matter particles. This means that all halo quantities are computed using **only** dark matter particles. I then assign star particles to the dark-matter halos in post-processing.

Ensure that rockstar_analysis and utilities directories are in your python path, then...

In [1]:
import rockstar_analysis as rockstar
import utilities as ut

In [2]:
# you can access the files as named or use the aliases in __init__.py to keep it shorter 
# for example, these are the same:

rockstar.rockstar_io
rockstar.io

<module 'rockstar_analysis.rockstar_io' from '/Users/awetzel/work/research/analysis/rockstar_analysis/rockstar_io.py'>

# read halo catalog

In [3]:
# read halo catalog at single snapshot (z = 0)

hal = rockstar.io.IO.read_catalogs('redshift', 0)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in rockstar_analysis.rockstar_io.IO():
* read 3484 halos from:  halo_600.hdf5

# in rockstar_analysis.rockstar_io.Particle():
* read 3484 halos with star particles from:  star_600.hdf5



In [5]:
# halo properties are stored as dictionary

for k in hal.keys():
    print(k)

accrete.rate
accrete.rate.100Myr
accrete.rate.tdyn
am.phantom
am.progenitor.main
axis.b/a
axis.c/a
descendant.snapshot
host.distance
host.index
host.velocity
host.velocity.rad
host.velocity.tan
id
infall.first.mass
infall.first.snapshot
infall.first.vel.circ.max
infall.mass
infall.snapshot
infall.vel.circ.max
major.merger.snapshot
mass
mass.180m
mass.200c
mass.200m
mass.500c
mass.bound
mass.half.snapshot
mass.lowres
mass.peak
mass.peak.snapshot
mass.vir
position
position.offset
progenitor.number
radius
scale.radius
scale.radius.klypin
spin.bullock
spin.peebles
tree.index
vel.circ.max
vel.circ.peak
vel.std
velocity
velocity.offset
lowres.mass.frac
star.form.time.100
star.form.time.50
star.form.time.90
star.form.time.95
star.form.time.dif.68
star.indices
star.mass
star.mass.neutral
star.massfraction
star.number
star.position
star.radius.50
star.radius.90
star.vel.circ.50
star.vel.std
star.vel.std.50
star.velocity


In [6]:
# you can read halo catalogs at all available snapshots
# by supplying None or 'all' as the input snapshot value.
# stored as a list of dictionaries, with list index same as snapshot index

hals = rockstar.io.IO.read_catalogs('redshift', None)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
! input 601 snapshot indices but found only 599 halo catalog files
* read 27 halos from:  halo_002.hdf5


* read 36 halos from:  halo_003.hdf5


* read 48 halos from:  halo_004.hdf5


* read 60 halos from:  halo_005.hdf5


* read 78 halos from:  halo_006.hdf5


* read 92 halos from:  halo_007.hdf5


* read 110 halos from:  halo_008.hdf5


* read 129 halos from:  halo_009.hdf5


* read 153 halos from:  halo_010.hdf5


* read 170 halos from:  halo_011.hdf5


* read 199 halos from:  halo_012.hdf5


* read 230 halos from:  halo_013.hdf5


* read 268 halos from:  halo_014.hdf5


* read 295 halos from:  halo_015.hdf5


* read 327 halos from:  halo_016.hdf5


* read 362 halos from:  halo_017.hdf5


* read 400 halos from:  halo_018.hdf5


* read 419 halos from:  halo_019.hdf5


* read 458 halos from:  halo_020.hdf5


* read 505 halos from:  halo_021.hdf5


* read 532 halos from:  halo_022.hdf5


* read 567 halos from:  halo_



* read 6330 halos from:  halo_155.hdf5


* read 6296 halos from:  halo_156.hdf5


* read 6290 halos from:  halo_157.hdf5


* read 6250 halos from:  halo_158.hdf5


* read 6295 halos from:  halo_159.hdf5
* read 6295 halos with star particles from:  star_159.hdf5


* read 6257 halos from:  halo_160.hdf5


* read 6240 halos from:  halo_161.hdf5


* read 6217 halos from:  halo_162.hdf5


* read 6203 halos from:  halo_163.hdf5


* read 6261 halos from:  halo_164.hdf5


* read 6168 halos from:  halo_165.hdf5
* read 6168 halos with star particles from:  star_165.hdf5


* read 6188 halos from:  halo_166.hdf5


* read 6221 halos from:  halo_167.hdf5


* read 6145 halos from:  halo_168.hdf5


* read 6102 halos from:  halo_169.hdf5


* read 6088 halos from:  halo_170.hdf5


* read 6092 halos from:  halo_171.hdf5


* read 6092 halos from:  halo_172.hdf5
* read 6092 halos with star particles from:  star_172.hdf5


* read 6084 halos from:  halo_173.hdf5


* read 6109 halos from:  halo_174.hdf5


*



* read 4489 halos from:  halo_333.hdf5


* read 4478 halos from:  halo_334.hdf5


* read 4465 halos from:  halo_335.hdf5


* read 4436 halos from:  halo_336.hdf5


* read 4475 halos from:  halo_337.hdf5


* read 4450 halos from:  halo_338.hdf5


* read 4415 halos from:  halo_339.hdf5


* read 4407 halos from:  halo_340.hdf5


* read 4411 halos from:  halo_341.hdf5


* read 4394 halos from:  halo_342.hdf5


* read 4385 halos from:  halo_343.hdf5


* read 4391 halos from:  halo_344.hdf5


* read 4373 halos from:  halo_345.hdf5


* read 4370 halos from:  halo_346.hdf5


* read 4369 halos from:  halo_347.hdf5


* read 4316 halos from:  halo_348.hdf5


* read 4318 halos from:  halo_349.hdf5


* read 4360 halos from:  halo_350.hdf5


* read 4353 halos from:  halo_351.hdf5


* read 4317 halos from:  halo_352.hdf5


* read 4320 halos from:  halo_353.hdf5


* read 4321 halos from:  halo_354.hdf5


* read 4320 halos from:  halo_355.hdf5


* read 4288 halos from:  halo_356.hdf5
* read 4288 halo



* read 3648 halos from:  halo_526.hdf5


* read 3701 halos from:  halo_527.hdf5


* read 3678 halos from:  halo_528.hdf5


* read 3693 halos from:  halo_529.hdf5


* read 3674 halos from:  halo_530.hdf5


* read 3631 halos from:  halo_531.hdf5


* read 3612 halos from:  halo_532.hdf5


* read 3644 halos from:  halo_533.hdf5


* read 3605 halos from:  halo_534.hdf5
* read 3605 halos with star particles from:  star_534.hdf5


* read 3571 halos from:  halo_535.hdf5


* read 3667 halos from:  halo_536.hdf5


* read 3644 halos from:  halo_537.hdf5


* read 3609 halos from:  halo_538.hdf5


* read 3620 halos from:  halo_539.hdf5
* read 3620 halos with star particles from:  star_539.hdf5


* read 3608 halos from:  halo_540.hdf5


* read 3618 halos from:  halo_541.hdf5


* read 3608 halos from:  halo_542.hdf5


* read 3631 halos from:  halo_543.hdf5


* read 3611 halos from:  halo_544.hdf5
* read 3611 halos with star particles from:  star_544.hdf5


* read 3605 halos from:  halo_545.hdf5


*

In [7]:
# halo catalog at z = 0 (snapshot 600)
hal_z0 = hals[600]

# halo catalog at z = 1 (snapshot 277)
hal_z1 = hals[277]

In [8]:
# by default, if you read multiple snapshots it will store so the halo catalog list index = snapshot index
# but if you just want to read a few snapshots and store as short list, you can do the following

hals = rockstar.io.IO.read_catalogs('redshift', [0, 1], all_snapshot_list=False)

hal_z1 = hals[0]
hal_z0 = hals[1]


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = [0, 1]:  using snapshot indices = [600 277]
  redshifts = [0. 1.]

* read 4878 halos from:  halo_277.hdf5
* read 4878 halos with star particles from:  star_277.hdf5


* read 3484 halos from:  halo_600.hdf5
* read 3484 halos with star particles from:  star_600.hdf5



# halo properties

In [18]:
hal = rockstar.io.IO.read_catalogs('redshift', 0)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in rockstar_analysis.rockstar_io.IO():
* read 3484 halos from:  halo_600.hdf5

# in rockstar_analysis.rockstar_io.Particle():
* read 3484 halos with star particles from:  star_600.hdf5



In [19]:
# halo properties are stored as dictionary

for k in hal.keys():
    print(k)

accrete.rate
accrete.rate.100Myr
accrete.rate.tdyn
am.phantom
am.progenitor.main
axis.b/a
axis.c/a
descendant.snapshot
host.distance
host.index
host.velocity
host.velocity.rad
host.velocity.tan
id
infall.first.mass
infall.first.snapshot
infall.first.vel.circ.max
infall.mass
infall.snapshot
infall.vel.circ.max
major.merger.snapshot
mass
mass.180m
mass.200c
mass.200m
mass.500c
mass.bound
mass.half.snapshot
mass.lowres
mass.peak
mass.peak.snapshot
mass.vir
position
position.offset
progenitor.number
radius
scale.radius
scale.radius.klypin
spin.bullock
spin.peebles
tree.index
vel.circ.max
vel.circ.peak
vel.std
velocity
velocity.offset
lowres.mass.frac
star.form.time.100
star.form.time.50
star.form.time.90
star.form.time.95
star.form.time.dif.68
star.indices
star.mass
star.mass.neutral
star.massfraction
star.number
star.position
star.radius.50
star.radius.90
star.vel.circ.50
star.vel.std
star.vel.std.50
star.velocity


In [ ]:
# 3-D position (particle_number x dimension_number array) [kpc comoving]

hal['position']

In [ ]:
# 3-D velocity (particle_number x dimension_number array) [km/s physical]

hal['velocity']

In [ ]:
# DM mass of halo [M_sun]
# I use 200m, 200 x the mean matter density, for the halo overdensity/virial definition

hal['mass']

In [ ]:
# but rockstar also stores total halo mass based on different virial definitions [M_sun]

print('{}\n{}\n{}'.format(hal['mass.200m'], hal['mass.vir'], hal['mass.200c']))

In [ ]:
# DM mass that is bound to halo [M_sun]

hal['mass.bound']

In [ ]:
# halo radius, again using 200m for the overdentiy/virial definition [kpc physical]

hal['radius']

In [ ]:
# NFW scale radius [kpc physical]

hal['scale.radius']

In [ ]:
# maximum of the circular velocity profile [km/s physical]

print(hal['vel.circ.max'])

In [ ]:
# standard deviation of the velocity (velocity disperion) [km/s physical]

print(hal['vel.std'])

In [11]:
# DM mass of low-resolution DM particles within R_200m [M_sun]

hal['mass.lowres']

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [20]:
# the fraction of DM mass within R_200m that is in low-resolution DM
# this is a derived quantity, so you need to call via the .prop() function

hal.prop('lowres.mass.frac')

array([0.        , 0.13160461, 0.        , ..., 0.        , 0.        ,
       0.        ], dtype=float32)

In [21]:
# index of the primary host halo in catalog list

hal['host.index']

array([1529, 1529, 1529, ..., 1529, 1529, 1529], dtype=int32)

In [22]:
# 3-D distance to the primary host halo [kpc physical]

hal['host.distance']

array([[   31.425781, -1607.4805  ,  -225.79297 ],
       [   67.69531 , -1573.8359  ,  -214.67188 ],
       [   54.07422 , -1601.0156  ,  -201.85156 ],
       ...,
       [   83.890625,   324.17188 ,   179.27344 ],
       [   82.35156 ,   370.0664  ,   148.3789  ],
       [   81.140625,   274.7539  ,   206.7539  ]], dtype=float32)

In [23]:
# total (scalar) distance to the primary host halo [kpc physical]
# this is a derived quantity, so you need to call via the .prop() function

hal.prop('host.distance.total')

array([1623.5651 , 1589.8511 , 1614.5956 , ...,  379.82104,  407.12064,
        353.2997 ], dtype=float32)

In [24]:
# 3-D velocity wrt the primary host halo [kpc physical]
# radial and tangential velocity wrt the primary host halo [kpc physical]

print(hal['host.velocity'])
print(hal['host.velocity.rad'])
print(hal['host.velocity.tan'])

[[ -38.893913 -100.065125  -67.59067 ]
 [ -39.01779  -163.35327   -67.31996 ]
 [  11.996011 -147.69128   -35.49998 ]
 ...
 [  77.52912   -19.48314    14.95499 ]
 [ -74.89891   -65.96134   -25.713802]
 [  88.39607   -27.73228    13.954126]]
[107.72095   169.13635   151.28896   ...   7.553853  -84.47989
   6.9007425]
[67.01091  64.277084 18.125307 ... 80.974976 59.034695 93.4347  ]


In [25]:
# use .prop() to compute derived quantities, such the log of the mass
# see rockstar.io.HaloDictionaryClass for all options for derived quantities

hal.prop('log mass')

array([7.197575 , 7.3127184, 7.3938875, ..., 7.112155 , 7.1817865,
       7.2128096], dtype=float32)

# halo catalogs with baryonic particle properties

I assign baryonic particle properties (such as stars) in post-processing, after generating the DM halo catalogs. I store those properties in a separate file, for example, star_600.hdf5. The above reader automatically looks if this file exists at the snapshot of interest and will read and append these properties to the halo catalog. Not all snapshots have baryonic particle properties.

Currently I impose a 15 kpc (physical) max radius to assign a star particle to a halo. 

In [26]:
# all stellar properties have dictionary keys as 'star.*' (ignore star.mass.rockstar)
# list of star particle properties
for k in hal:
    if 'star.' in k:
        print(k)

star.form.time.100
star.form.time.50
star.form.time.90
star.form.time.95
star.form.time.dif.68
star.indices
star.mass
star.mass.neutral
star.massfraction
star.number
star.position
star.radius.50
star.radius.90
star.vel.circ.50
star.vel.std
star.vel.std.50
star.velocity


In [27]:
# find halos with star particles

his = ut.array.get_indices(hal['star.mass'], [1, Inf])

In [28]:
# mass of all star particles in halo [M_sun]

hal['star.mass'][his]

array([2.7740931e+05, 4.0072131e+05, 1.9278013e+08, 1.6913989e+06,
       2.9055053e+05, 3.6715422e+06, 1.3627845e+06, 1.1866028e+11,
       5.9258769e+05, 1.4315092e+07, 3.5678050e+05, 2.3205416e+05,
       2.6500165e+06, 2.0755903e+05, 4.1515209e+05, 2.8523103e+09,
       1.4802192e+07], dtype=float32)

In [29]:
# number of star particles in halo [M_sun]

hal['star.number'][his]

array([      6,       8,    4754,      41,       7,      90,      33,
       2285125,      13,     355,       8,       5,      63,       5,
            10,   65829,     368], dtype=int32)

In [30]:
# radius that encloses 50%, 90% of the stellar mass [kpc physical]

print(hal['star.radius.50'][his])
print(hal['star.radius.90'][his])

[2.7605097 2.8120294 3.9363506 2.3187587 3.0943637 2.773992  3.5594394
 2.0976882 2.5729434 3.4748592 1.7299412 2.6946738 2.885782  2.2415848
 2.2643697 4.1248717 2.8092728]
[ 9.917109   3.7087386  8.764568   5.5444274  5.9604287  8.241288
  8.58264    6.666064   4.631308   8.758817   7.0835123  3.9401145
  7.474184   3.1880832 14.554998   8.811111   6.023005 ]


In [31]:
# can compute stellar density (within R_50) as a derived property [M_sun / kpc^3]

hal.prop('star.density.50', his)

array([1.5741083e+03, 2.1511184e+03, 3.7727872e+05, 1.6194246e+04,
       1.1705474e+03, 2.0531199e+04, 3.6071462e+03, 1.5344896e+09,
       4.1528218e+03, 4.0725262e+04, 8.2259951e+03, 1.4156377e+03,
       1.3162530e+04, 2.1996699e+03, 4.2682178e+03, 4.8511735e+06,
       7.9694008e+04], dtype=float32)

In [32]:
# stellar velocity dispersion (standard deviation) at R_50 [km / s]

hal['star.vel.std.50'][his]

array([ 22.083683,  17.886648,  33.79134 ,  19.469017,  24.443657,
        19.544634,  11.421447, 338.0491  ,  17.776804,  15.791031,
        27.349167,  22.824812,  20.027245,  16.050514,  19.461723,
        66.77299 ,  25.002712], dtype=float32)

In [33]:
# center-of-mass position and velocity of star particles [kpc comoving]

print(hal['star.position'][his])
print(hal['star.velocity'][his])

[[41781.56  43480.15  46658.395]
 [41830.27  43030.49  46740.45 ]
 [41622.32  43976.594 46311.254]
 [41639.176 43975.79  46519.863]
 [41891.668 43969.49  46325.54 ]
 [41851.258 44105.36  46358.438]
 [41853.625 44090.336 46375.69 ]
 [41821.977 44122.    46288.445]
 [41831.31  44127.754 46443.855]
 [41772.45  44267.758 46189.91 ]
 [41832.285 44397.598 46186.855]
 [41714.55  44149.48  46278.426]
 [41746.652 44401.58  46368.426]
 [41811.88  44248.215 46335.656]
 [41845.875 44250.89  46238.785]
 [42326.566 46242.703 46897.89 ]
 [41710.25  44243.83  46567.26 ]]
[[  -9.464741   104.19139     -4.5497684]
 [ -18.685646    92.534355    15.438123 ]
 [-102.12357    126.88925     60.099598 ]
 [ -92.73803    101.32438     96.83005  ]
 [-128.08545    128.89117    204.56511  ]
 [-187.8551      42.681217  -100.38308  ]
 [  25.128942   111.413994   -63.950726 ]
 [ -49.453175    73.01806     97.339516 ]
 [ -21.407557   -60.986347   198.22601  ]
 [ -61.37039    -50.457153   145.8585   ]
 [  57.688744   -3

In [34]:
# time (age of Universe) when galaxy formed 50%, 90%, etc of its current stellar mass [Gyr]

print(hal['star.form.time.50'][his])
print(hal['star.form.time.90'][his])

[1.0796949  0.860665   7.4421144  4.444367   0.9286473  3.3452203
 2.8379028  6.9067817  1.0172235  5.11471    1.3203455  0.61192775
 3.2727437  1.5335069  0.87201387 7.5832977  4.4236155 ]
[ 1.079912    0.86157835 11.915186    7.9318376   0.929332    5.8099756
  5.4541674  11.299019    1.1361079   8.031222    1.3231392   0.61205685
  5.316226    1.5336047   1.5286106  12.264062   10.433421  ]


In [35]:
# can convert this to lookback-time via derived property [Gyr]

hal.prop('star.form.time.lookback.50', his)

array([12.719052 , 12.938082 ,  6.3566327,  9.35438  , 12.8701   ,
       10.4535265, 10.960844 ,  6.8919654, 12.781524 ,  8.684037 ,
       12.478401 , 13.186819 , 10.526003 , 12.26524  , 12.926733 ,
        6.2154493,  9.375132 ], dtype=float32)

In [36]:
# indices of member star particles in the particle list at the same snapshot
# for example, star particles assigned to halo 0 would be part_indices = hal['star.indies'][0]
# then if you read in the particle snapshot, you can access member star particles via 
# part['star'][property_name][part_indices]

hal['star.indices'][his[0]]

array([  37837,   57152,   57153,   57154,   57155, 1139140], dtype=int32)

# additional information stored in sub-dictionaries

In [15]:
# dictionary of useful information about the simulation

hal.info

{'dark.particle.mass': 281448.71794871794,
 'gas.particle.mass': 56538.26342899189,
 'box.length/h': 60000.0,
 'box.length': 85470.08547008547,
 'simulation.name': '',
 'catalog.kind': 'halo.catalog'}

In [16]:
# dictionary class of information about the cosmology of the simulation

hal.Cosmology

{'omega_lambda': 0.728,
 'omega_matter': 0.272,
 'omega_baryon': 0.0455,
 'omega_curvature': 0.0,
 'omega_dm': 0.22650000000000003,
 'baryon.fraction': 0.16727941176470587,
 'hubble': 0.7020000000000001,
 'sigma_8': 0.807,
 'n_s': 0.961,
 'w': -1.0}

In [17]:
# dictionary of information about this snapshot's index, scale-factor, redshift, time, lookback-time

hal.snapshot

{'index': 600,
 'scalefactor': 1.0,
 'redshift': 0.0,
 'time': 13.798746882657936,
 'time.lookback': 0.0,
 'time.hubble': 13.928664125669}

In [37]:
# dictionary of arrays about *all* snapshots of the simulation

print(hal.Snapshot.keys())
print(hal.Snapshot['redshift'])

dict_keys(['index', 'scalefactor', 'redshift', 'time', 'time.width'])
[9.90000000e+01 1.90000000e+01 1.50000000e+01 1.46059113e+01
 1.42307692e+01 1.38732395e+01 1.35321102e+01 1.32062778e+01
 1.28947372e+01 1.25965662e+01 1.23109245e+01 1.20370369e+01
 1.17741938e+01 1.15217390e+01 1.12790699e+01 1.10456276e+01
 1.08208952e+01 1.06043959e+01 1.03956833e+01 1.01943464e+01
 1.00000000e+01 9.81967163e+00 9.64516163e+00 9.47619057e+00
 9.31250000e+00 9.15384579e+00 9.00000000e+00 8.84375000e+00
 8.69230747e+00 8.54545403e+00 8.40298557e+00 8.26470566e+00
 8.13043499e+00 8.00000000e+00 7.86153841e+00 7.72727251e+00
 7.59701490e+00 7.47058821e+00 7.34782600e+00 7.22857141e+00
 7.11267614e+00 7.00000000e+00 6.89743567e+00 6.79746819e+00
 6.69999981e+00 6.60493851e+00 6.51219511e+00 6.42168665e+00
 6.33333349e+00 6.24705887e+00 6.16279078e+00 6.08045959e+00
 6.00000000e+00 5.92307711e+00 5.84782600e+00 5.77419329e+00
 5.70212793e+00 5.63157892e+00 5.56250000e+00 5.49484539e+00
 5.42857122e+00

# halo merger trees

The Rockstar halo finder treats each snapshot as independent, so halos at different snapshots do not know about each other. ConsistentTrees produces halo merger trees that link halos over time.

Note: ConsistentTrees applies some smoothing and physical consistency checks on halos over time, which leads to two important differences from the halo catalog: (1) not every halo in the catalog exists in the merger tree (especially those that are marginally resolved) (2) some halos in the merger tree are 'phantom' halos that have been interpolated across snapshots but do not exist in the halo catalog at that snapshot.

Like with the halo catalogs, the reader automatically looks if baryonic particle property files exists at each snapshot and will read and append these properties to the halo merger trees. Again, not all snapshots have baryonic particle properties, so not all halos in the tree will have valid values for these.

In [38]:
# read halo merger trees across all snapshots
# this is a concatenated list of all halos across all snaphots, with pointers to progenitor and descendant halos

halt = rockstar.io.IO.read_tree()


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
* read 2268668 halos from:  tree.hdf5
  
* assigning star properties to halo merger trees
* read 673 halos with star particles from:  star_026.hdf5


/Applications/anaconda/lib/python3.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)


* read 1234 halos with star particles from:  star_033.hdf5
* read 2132 halos with star particles from:  star_041.hdf5
* read 3644 halos with star particles from:  star_052.hdf5
* read 3950 halos with star particles from:  star_055.hdf5
* read 4220 halos with star particles from:  star_057.hdf5
* read 4630 halos with star particles from:  star_060.hdf5
* read 5115 halos with star particles from:  star_064.hdf5
* read 5407 halos with star particles from:  star_067.hdf5
* read 5631 halos with star particles from:  star_071.hdf5
* read 5930 halos with star particles from:  star_075.hdf5
* read 6141 halos with star particles from:  star_079.hdf5
* read 6348 halos with star particles from:  star_083.hdf5
* read 6565 halos with star particles from:  star_088.hdf5
* read 6622 halos with star particles from:  star_091.hdf5
* read 6575 halos with star particles from:  star_093.hdf5
* read 6692 halos with star particles from:  star_096.hdf5
* read 6778 halos with star particles from:  star_099.hd

In [39]:
# halo merger tree properties are stored as dictionary

for k in halt.keys():
    print(k)

am.phantom
am.progenitor.main
axis.b/a
axis.c/a
catalog.index
central.index
central.local.index
descendant.index
descendant.snapshot
dindex
final.index
host.distance
host.index
host.velocity
host.velocity.rad
host.velocity.tan
major.merger.snapshot
mass
mass.180m
mass.200c
mass.200m
mass.500c
mass.bound
mass.lowres
mass.vir
position
position.offset
progenitor.co.dindex
progenitor.co.index
progenitor.last.dindex
progenitor.main.index
progenitor.main.last.dindex
progenitor.number
radius
scale.radius
scale.radius.klypin
snapshot
spin.bullock
spin.peebles
tid
vel.circ.max
vel.std
velocity
velocity.offset
lowres.mass.frac
star.form.time.100
star.form.time.50
star.form.time.90
star.form.time.95
star.form.time.dif.68
star.indices
star.mass
star.mass.neutral
star.massfraction
star.number
star.position
star.radius.50
star.radius.90
star.vel.circ.50
star.vel.std
star.vel.std.50
star.velocity


In [22]:
# now each halo has a corredponding snapshot index

halt['snapshot']

array([600, 599, 599, ..., 543, 542, 541], dtype=int32)

In [40]:
# so, get all halos at snapshot 600 (z = 0) and print their masses

hindices = np.where(halt['snapshot'] == 600)[0]
print(halt['mass'][hindices])

[1.0446296e+12 6.0505699e+11 2.0990027e+11 ... 5.9103990e+06 4.2217950e+06
 3.3773505e+06]


In [41]:
# alternately, get catalog of halos only at snapshot 600 from tree

hal = rockstar.io.IO.get_catalog_from_tree(halt, 600)

In [43]:
hal['mass']

array([1.0446296e+12, 6.0505699e+11, 2.0990027e+11, ..., 5.9103990e+06,
       4.2217950e+06, 3.3773505e+06], dtype=float32)

In [44]:
# whether halo is 'phantom' interpolation across snapshots

halt['am.phantom']

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [45]:
# tree index of its descendant at a later (usually the next) snapshot
# ConsistentTrees allows only one descendant per halo

print(halt['descendant.index'])

# for example, get descendant of halo index 100 and print its mass
hindex = 100
desc_index = halt['descendant.index'][hindex]
print(desc_index, halt['mass'][desc_index])

[-2268669        0        0 ...  2268664  2268665  2268666]
84 13791026.0


In [46]:
# number of progenitor halos (can be arbitrarily large) at an earler (usually the previous) snapshot

halt['progenitor.number']

array([2, 4, 1, ..., 1, 1, 0], dtype=int32)

In [47]:
# tree index of main (most massive) progenitor
# iteratively loop over this to get list of main progenitors going back in time

halt['progenitor.main.index']

array([       1,        3,        7, ...,  2268666,  2268667, -2268669],
      dtype=int32)

In [48]:
# whether I am the main (most massive) progenitor of my descendant

halt['am.progenitor.main']

array([1, 1, 0, ..., 1, 1, 1], dtype=int32)

In [49]:
# tree index of next co-progenitor

halt['progenitor.co.index']

array([-2268669,        2, -2268669, ..., -2268669, -2268669, -2268669],
      dtype=int32)

In [50]:
# tree index of my descendant at the final snapshot (z = 0)

halt['final.index']

array([      0,       0,       0, ..., 2268608, 2268608, 2268608],
      dtype=int32)

In [51]:
# example workflow

# start with a halo with tree index 0 (at z = 0)
hindex = 0
print(halt['snapshot'][hindex])
print(halt['mass'][hindex])

# find its progenitors, list their mass
prog_index = halt['progenitor.main.index'][hindex]
prog_indices = []
while prog_index >= 0:
    prog_indices.append(prog_index)
    prog_index = halt['progenitor.co.index'][prog_index]
print(prog_indices)
print(halt['mass'][prog_indices])

# for the main progenitor, find its progenitors, list their mass
hindex = prog_indices[0]
prog_index = halt['progenitor.main.index'][hindex]
prog_indices = []
while prog_index >= 0:
    prog_indices.append(prog_index)
    prog_index = halt['progenitor.co.index'][prog_index]
print(prog_indices)
print(halt['mass'][prog_indices])

600
1044629600000.0
[1, 2]
[1.0447863e+12 6.1918805e+06]
[3, 4, 5, 6]
[1.04423077e+12 1.23837610e+07 1.94202280e+07 1.63233620e+07]


In [52]:
# get list of main progenitors as far back as can go

hindex = 0
prog_main_index = hindex
prog_main_indices = []
while prog_main_index >= 0:
    prog_main_indices.append(prog_main_index)
    prog_main_index = halt['progenitor.main.index'][prog_main_index]

print(prog_main_indices)
print(halt['mass'][prog_main_indices])
print(halt['position'][prog_main_indices])

[0, 1, 3, 8, 13, 18, 23, 29, 35, 41, 47, 53, 61, 73, 88, 104, 121, 139, 158, 179, 204, 231, 259, 287, 316, 347, 379, 412, 447, 483, 520, 558, 596, 635, 676, 718, 762, 808, 854, 900, 948, 996, 1045, 1095, 1145, 1199, 1253, 1307, 1362, 1420, 1480, 1540, 1603, 1666, 1731, 1799, 1868, 1938, 2007, 2077, 2151, 2226, 2303, 2381, 2458, 2535, 2611, 2687, 2765, 2845, 2929, 3015, 3102, 3190, 3279, 3370, 3461, 3554, 3646, 3740, 3837, 3935, 4034, 4134, 4237, 4344, 4457, 4572, 4688, 4806, 4925, 5048, 5172, 5298, 5423, 5549, 5677, 5805, 5933, 6061, 6190, 6321, 6453, 6585, 6718, 6851, 6985, 7121, 7259, 7396, 7540, 7682, 7825, 7966, 8107, 8246, 8389, 8537, 8688, 8843, 8999, 9157, 9315, 9475, 9635, 9793, 9951, 10111, 10275, 10439, 10606, 10774, 10943, 11114, 11288, 11461, 11635, 11811, 11987, 12162, 12337, 12514, 12692, 12872, 13055, 13240, 13428, 13618, 13815, 14011, 14207, 14405, 14607, 14810, 15015, 15223, 15431, 15640, 15850, 16062, 16276, 16494, 16714, 16934, 17157, 17381, 17605, 17831, 18058, 1828

In [53]:
# halt.prop() computes derived quantities and can make walking the tree easier

# for halo with tree index = 0, get its main progenitors going back as far as can (including self)
hindex = 0
prog_indices = halt.prop('progenitor.main.indices', hindex)

# print mass history
print(prog_indices)
print(halt['mass'][prog_indices])

[     0      1      3      8     13     18     23     29     35     41
     47     53     61     73     88    104    121    139    158    179
    204    231    259    287    316    347    379    412    447    483
    520    558    596    635    676    718    762    808    854    900
    948    996   1045   1095   1145   1199   1253   1307   1362   1420
   1480   1540   1603   1666   1731   1799   1868   1938   2007   2077
   2151   2226   2303   2381   2458   2535   2611   2687   2765   2845
   2929   3015   3102   3190   3279   3370   3461   3554   3646   3740
   3837   3935   4034   4134   4237   4344   4457   4572   4688   4806
   4925   5048   5172   5298   5423   5549   5677   5805   5933   6061
   6190   6321   6453   6585   6718   6851   6985   7121   7259   7396
   7540   7682   7825   7966   8107   8246   8389   8537   8688   8843
   8999   9157   9315   9475   9635   9793   9951  10111  10275  10439
  10606  10774  10943  11114  11288  11461  11635  11811  11987  12162
  1233

In [55]:
# print stellar mass history - recall that not all snapshots necessarily have star particle information

print(halt['star.mass'][prog_indices])

[1.18660276e+11            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 1.18752903e+11
            nan            nan            nan            nan
            nan 1.18552773e+11            nan            nan
            nan            nan            nan 1.18551863e+11
            nan            nan            nan            nan
            nan 1.17996028e+11            nan            nan
            nan            nan            nan 1.17655233e+11
            nan            nan            nan            nan
            nan 1.17186454e+11            nan            nan
            nan            nan 1.17338194e+11            nan
            nan            nan            nan            nan
 1.17197685e+11            nan            nan            nan
            nan 1.16887175e+11            nan            nan
            nan         

In [42]:
# for halo with tree index = 1, get all of its progenitors at previous snapshot, print their masses

hindex = 1
prog_indices = halt.prop('progenitor.indices', hindex)

print(prog_indices)
print(halt['mass'][prog_indices])

[3 4 5 6]
[1.04423077e+12 1.23837610e+07 1.94202280e+07 1.63233620e+07]


In [56]:
# for halo with tree index = 123456, get its descendants going forward as far as can (including self)

hindex = 123456
desc_indices = halt.prop('descendant.indices', hindex)

# print future mass growth
print(desc_indices)
print(halt['mass'][desc_indices])

[123456 122426 121405 120390 119380 118377 117381 116387 115407 114431
 113460 112498 111541 110591 109647 108713 107784 106860 105945 105038
 104137 103244 102353 101469 100593  99722  98855  97999  97142  96289
  95445  94604  93765  92934  92111  91291  90472  89662  88852  88052
  87259  86470  85688  84911  84139  83372  82611  81859  81110  80367
  79625  78890  78162  77435  76713  76002  75299  74601  73905  73213
  72526  71846  71168  70490  69823  69157  68502  67855  67215  66579
  65946  65319  64698  64080  63467  62860  62264  61669  61076  60496
  59918  59349  58792  58244  57704  57171  56642  56120  55600  55085
  54574  54065  53558  53057  52558  52066  51580  51098  50623  50149
  49679  49212  48751  48291  47835  47384  46934  46487  46039  45597
  45162  44731  44308  43887  43471  43061  42653  42248  41847  41448
  41055  40668  40283  39902  39523  39146  38774  38404  38034  37672
  37310  36949  36590  36234  35883  35535  35190  34853  34518  34181
  3385

# interfacting between halo catalog and merger trees

Each halo in the merger trees has a pointers to its array index in the halo catalog: 'catalog.index'

Conversely, each halo in the catalog has a pointer to its array index in the halo merger trees: 'tree.index'

You can use these to go back and forth between the two.

Note: tree ids/indices are unique across all snapshots, but halo catalog ids/indices are unique only at a given snapshot

In [ ]:
# read halo merger trees across all snapshots
halt = rockstar.io.IO.read_tree()

# read halo catalog at each snapshot
hals = rockstar.io.IO.read_catalogs(snapshot_values='all')


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
* read 2268668 halos from:  tree.hdf5
  
* assigning star properties to halo merger trees
* read 673 halos with star particles from:  star_026.hdf5


/Applications/anaconda/lib/python3.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)


* read 1234 halos with star particles from:  star_033.hdf5
* read 2132 halos with star particles from:  star_041.hdf5
* read 3644 halos with star particles from:  star_052.hdf5
* read 3950 halos with star particles from:  star_055.hdf5
* read 4220 halos with star particles from:  star_057.hdf5
* read 4630 halos with star particles from:  star_060.hdf5
* read 5115 halos with star particles from:  star_064.hdf5
* read 5407 halos with star particles from:  star_067.hdf5
* read 5631 halos with star particles from:  star_071.hdf5
* read 5930 halos with star particles from:  star_075.hdf5
* read 6141 halos with star particles from:  star_079.hdf5
* read 6348 halos with star particles from:  star_083.hdf5
* read 6565 halos with star particles from:  star_088.hdf5
* read 6622 halos with star particles from:  star_091.hdf5
* read 6575 halos with star particles from:  star_093.hdf5
* read 6692 halos with star particles from:  star_096.hdf5
* read 6778 halos with star particles from:  star_099.hd

* read 6558 halos from:  halo_090.hdf5


* read 6622 halos from:  halo_091.hdf5
* read 6622 halos with star particles from:  star_091.hdf5


* read 6574 halos from:  halo_092.hdf5


* read 6575 halos from:  halo_093.hdf5
* read 6575 halos with star particles from:  star_093.hdf5


* read 6708 halos from:  halo_094.hdf5


* read 6664 halos from:  halo_095.hdf5


* read 6692 halos from:  halo_096.hdf5
* read 6692 halos with star particles from:  star_096.hdf5


* read 6673 halos from:  halo_097.hdf5


* read 6780 halos from:  halo_098.hdf5


* read 6778 halos from:  halo_099.hdf5
* read 6778 halos with star particles from:  star_099.hdf5


* read 6722 halos from:  halo_100.hdf5


* read 6709 halos from:  halo_101.hdf5


* read 6704 halos from:  halo_102.hdf5
* read 6704 halos with star particles from:  star_102.hdf5


* read 6747 halos from:  halo_103.hdf5


* read 6761 halos from:  halo_104.hdf5


* read 6769 halos from:  halo_105.hdf5
* read 6769 halos with star particles from:  star_1

In [ ]:
# starting from the halo catalog at z = 0, get index of the halo in the merger trees
hal = hals[600]

cat_index = 100  # random halo of interest
print(hal['mass'][cat_index])
tree_index = hal['tree.index'][cat_index]
print(tree_index)
print(halt['mass'][tree_index])

In [ ]:
# conversely, starting from the halo merger trees, get index of the halo in the snapshot catalog
# because halo catalog indices are *not* unique across snapshots, 
# you also need to use which snapshot index the halo points to

tree_index = 100  # random halo of interest
print(halt['mass'][tree_index])
snapshot_index = halt['snapshot'][tree_index]  # index of snapshot in halo catalog
cat_index = halt['catalog.index'][tree_index]  # halo catalog index at snapshot
print(snapshot_index, cat_index)
print(hals[snapshot_index]['mass'][cat_index])

See rockstar.analysis for examples of high-level analysis, including plotting these data.

See utilities package for low-level functions that may be useful.